<?php require('template/header.phtml') ?>


<section class="container container-fluid">
    <!-- Login/Register -->
    <section class="container">
        <div class="panel-group" id="accordion">

            <!-- Users -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#CollapseExpiry">Manage Advert Expiry</a>
                    </h4>
                </div>
                <div id="CollapseExpiry" class="panel-collapse collapse in">
                    <div class="panel-body">
                        <div class="col-md-3"></div>
                        <div class="col-md-6 col-xs-12 center-block">
                            <form name="ChangeAdvertExpiry" class="form" action="<?php echo htmlentities($_SERVER['PHP_SELF']) ?>" method="post">
                                <label>
                                    Change Advert Expiry.<br/>
                                    <?php
                                    if(isset($view->expiryTime))
                                        echo "Current expiry rate is: $view->expiryTime";
                                    else
                                        echo "Current expiry rate is: 2 Weeks";
                                    ?>
                                </label>
                                <select name="expiryTime" class="form-control">
                                    <option value="1 week">1 Week</option>
                                    <option value="2 weeks">2 Weeks</option>
                                    <option value="1 month">1 Month</option>
                                </select>
                                <br />
                                <input type="submit" value="Change Expiry Rate" name="changeAdvertExpirySubmit" class="btn-success form-control">
                            </form>
                        </div>
                        <div class="col-md-3"></div>
                    </div>
                </div>
            </div>

            <!-- Users -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#CollapseUsers">Manage Users</a>
                    </h4>
                </div>
                <div id="CollapseUsers" class="panel-collapse collapse">
                    <div class="panel-body">
                        <div class="col-md-1"></div>
                        <div class="col-md-10 col-xs-12 center-block">
                            <div class="col-md-12" style="border: solid">
                                <div class="col-md-2">ID</div>
                                <div class="col-md-2">First Name</div>
                                <div class="col-md-2">Last Name</div>
                                <div class="col-md-2">Email Name</div>
                                <div class="col-md-2">Delete User</div>
                                <div class="col-md-2">Admin User</div>
                            </div>
                            <span class="col-md-12" style="padding-top: 5px"></span>
                                <?php
                                if(isset($view->usersTable))
                                {
                                    echo $view->usersTable;
                                }
                                ?>
                        </div>
                        <div class="col-md-1"></div>
                    </div>
                </div>
            </div>

            <!-- Adverts -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#CollapseAdverts">Manage Adverts</a>
                    </h4>
                </div>
                <div id="CollapseAdverts" class="panel-collapse collapse">
                    <div class="panel-body">
                        <div class="col-md-1"></div>
                        <div class="col-md-10 col-xs-12 center-block">
                            <div class="col-md-12" style="border: solid">
                                <div class="col-md-1">ID</div>
                                <div class="col-md-1">User ID</div>
                                <div class="col-md-2">Title</div>
                                <div class="col-md-2">Category</div>
                                <div class="col-md-2">Date</div>
                                <div class="col-md-2">Price(£)</div>
                                <div class="col-md-2">Delete</div>
                            </div>
                            <span class="col-md-12" style="padding-top: 5px"></span>
                            <?php
                            if(isset($view->advertsTable))
                            {
                                echo $view->advertsTable;
                            }
                            ?>
                        </div>
                        <div class="col-md-1"></div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</section>

<?php require('template/footer.phtml') ?>
