<?php require('template/header.phtml') ?>
<div class="container">
    <?php
    if(isset($view->advert))
    {
        echo $view->advert;
        echo "<br>" .
            "<form name='advertOptions' action='" . $_SERVER['PHP_SELF'] . "?advert=$view->PKCode' method='post'>";

        if(! $view->isMadeByUser)
        {
            echo "<div class='col-md-4'>
                    
                    <a class='btn btn-success' href='mailto:$view->advertEmail'>
                    <span class=\"glyphicon glyphicon-envelope\"></span> 
                    Message Seller
                    </a>
                    
                  </div>";
//<button name='msgSeller' class='btn btn-success'>

            if($view->isOnWishlist)
            {
                echo "<div class='col-md-4'><button name='wishListRemove' class=\"btn btn-success\"><span class=\"glyphicon glyphicon-minus\"></span> Remove from Wish List</button></div>";
            }
            else
            {
                echo "<div class='col-md-4'><button name='wishList' class=\"btn btn-success\"><span class=\"glyphicon glyphicon-plus\"></span> Add to Wish List</button></div>";
            }
        }
        else
        {
            echo "<div class='col-md-4'><button name='deleteAdvert' class=\"btn btn-danger\"><span class=\"glyphicon glyphicon-remove\"></span> Delete Advert</button></div>";
        }

        echo "</form>" .
            "</div>";
    }
    else
    {
        echo "<h2>It appears this advert doesn't exist</h2>";
        echo "<h3><a href='/index.php'>Find other products</a></h3>";
    }
    ?>
</div>
<?php require('template/footer.phtml') ?>