<?php require('template/header.phtml') ?>


<section class="container container-fluid">
    <!-- Banner Image -->
    <section class="row">
        <div class="col-*-*">
<!--            <img src="http://placehold.it/1900x700" width="100%"/>-->
            <img src="/images/homepage/banner.png" width="100%"/>
        </div>
    </section>

    <!-- Categories -->
    <section class="container">
        <h2 class="text-center">Categories</h2>

        <div id="categories" class="text-center container container-fluid col-md-12">
            <div class="text-center col-md-4">
                <a href="/search.php?c=violin">
                <h3>Violins</h3>
<!--                <img src="http://placehold.it/150x150" class="category-img"/>-->
                <img src="/images/homepage/violin.png" class="category-img"/>
                </a>
            </div>
            <div class="text-center col-md-4">
                <a href="/search.php?c=viola">
                <h3>Violas</h3>
<!--                <img src="http://placehold.it/150x150" class="category-img"/>-->
                <img src="/images/homepage/viola.png" class="category-img"/>
                </a>
            </div>
            <div class="text-center col-md-4">
                <a href="/search.php?c=cello">
                <h3>Cellos</h3>
<!--                <img src="http://placehold.it/150x150" class="category-img"/>-->
                <img src="/images/homepage/cello.png" class="category-img"/>
                </a>
            </div>
            <div class="text-center col-md-4">
                <a href="/search.php?c=bass">
                <h3>Double Basses</h3>
<!--                <img src="http://placehold.it/150x150" class="category-img"/>-->
                <img src="/images/homepage/bass.png" class="category-img"/>
                </a>
            </div>
            <div class="text-center col-md-4">
                <a href="/search.php?c=music">
                    <h3>Sheet Music</h3>
<!--                    <img src="http://placehold.it/150x150" class="category-img"/>-->
                    <img src="/images/homepage/music.png" class="category-img"/>
                </a>
            </div>
            <div class="text-center col-md-4">
                <a href="/search.php?c=accessory">
                    <h3>Accessories</h3>
<!--                    <img src="http://placehold.it/150x150" class="category-img"/>-->
                    <img src="/images/homepage/accessory.png" class="category-img"/>
                </a>
            </div>
        </div>

    </section>
</section>


<?php require('template/footer.phtml') ?>
