<?php require('template/header.phtml') ?>

<h3>Lipsum Page</h3>
<p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sed lobortis nunc, in auctor mi. Donec sed molestie libero. Aenean tempor ut metus at lacinia. Ut volutpat tortor eu ultrices rhoncus. Nam nec bibendum sapien. Ut eu magna eu lorem sodales volutpat. Cras imperdiet sed eros vel imperdiet.
</p>
<p>
    Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla fermentum, lorem sit amet congue iaculis, ex dolor vulputate odio, finibus vulputate odio ante quis ante. Duis ut nulla sed ante vehicula viverra. Aliquam at mi volutpat, gravida tellus eget, accumsan lorem. Vestibulum eu lacus eget tellus egestas dapibus quis non purus. Quisque sit amet dolor eget nunc malesuada iaculis nec vitae est. Curabitur sed neque sed lorem gravida sagittis in eu odio. Donec sit amet quam ex.
</p>
<p>
    Ut purus libero, mattis ut dignissim nec, eleifend sed augue. Curabitur condimentum ex ut sem ornare, sit amet ultrices justo gravida. Etiam turpis nibh, vulputate sit amet aliquam non, pellentesque porttitor est. Suspendisse potenti. Mauris bibendum convallis tristique. Sed pulvinar blandit massa, sed porta odio cursus at. Pellentesque posuere lectus dui, ac vehicula enim cursus interdum. Sed condimentum ipsum a tellus molestie vulputate. Nunc leo ex, cursus sed justo fringilla, varius varius dui. Aliquam sagittis, ipsum ut tincidunt finibus, purus lectus convallis dolor, eget convallis velit tellus nec ante.
</p>
<div id="advert-picture-slides" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#advert-picture-slides" data-slide-to="0" class="active"></li>
        <li data-target="#advert-picture-slides" data-slide-to="1"></li>
        <li data-target="#advert-picture-slides" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item active animated fadeInRight">
            <img src="/images/uploads/Ic3gOSSmppP17v4IfbHs.jpg" alt="" class="img-responsive" />
        </div>

        <div class="item animated fadeInRight">
            <img src="/images/uploads/iQoSnuVB1WOttSe5gUbx.jpg" alt="" class="img-responsive" />
        </div>

        <div class="item animated fadeInRight">
            <img src="/images/uploads/KKFOtRdqRGKEiUCSspxh.jpg" alt="" class="img-responsive" />
        </div>
    </div>

    <!-- Controls -->
    <div id="my-carousel" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            ...
        </div>
    </div>

    <a class="left carousel-control" href="#advert-picture-slides" data-slide="prev">
        <span class="icon-prev"></span>
    </a>

    <a class="right carousel-control" href="#advert-picture-slides" data-slide="next">
        <span class="icon-next"></span>
    </a>
</div>
<?php require('template/footer.phtml') ?>
