<?php require('template/header.phtml') ?>


<section class="container container-fluid">
    <!-- Login/Register -->
    <section class="container">
        <div class="panel-group" id="accordion">

            <!-- Login Form -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#CollapseLogin">Login</a>
                    </h4>
                </div>
                <div id="CollapseLogin" class="panel-collapse collapse in">
                    <div class="panel-body">
                        <div class="col-md-3"></div>
                        <form class="col-md-6 col-xs-12 center-block" name="Login-Form"
                              onsubmit="return validateLoginForm()"
                              action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']); ?>" method="post">
                            <label>Email</label>
                            <input type="email" class="form-control" name="LoginEmail" placeholder="name@example.com" required/>
                            <label>Password</label>
                            <input type="password" class="form-control" name="LoginPassword" placeholder="password" required/>
                            <br />
                            <input type="submit" name="login" value="Login" class="btn btn-default btn-sm form-control" />
                        </form>
                        <div class="col-md-3"></div>
                    </div>
                </div>
            </div>

            <!-- Registration Form -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#CollapseRegister">Register</a>
                    </h4>
                </div>
                <div id="CollapseRegister" class="panel-collapse collapse">
                    <div class="panel-body">
                        <div class="col-md-3"></div>
                        <form class="col-md-6 col-xs-12 center-block" name="Registration-Form"
                              onSubmit="return validateRegisterForm()"
                              action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']); ?>" method="post">
                            <br>
                            <label>First Name</label>
                            <input type="text" class="form-control" name="RegistrationFirstName" />
                            <label>Surname</label>
                            <input type="text" class="form-control" name="RegistrationSurname" />
                            <label>Email</label>
                            <input type="email" class="form-control" name="RegistrationEmail" />
                            <label>Confirm Email</label>
                            <input type="email" class="form-control" name="RegistrationEmailConfirmation" />
                            <label>Password <small>(Must be at least 8 characters)</small></label>
                            <input type="password" class="form-control" name="RegistrationPassword" />
                            <label>Confirm Password</label>
                            <input type="password" class="form-control" name="RegistrationPasswordConfirmation" />
                            <label>Address</label>
                            <textarea name="RegistrationAddress" class="form-control" ></textarea>
                            <label>Mobile Number</label>
                            <input type="text" class="form-control" name="RegistrationMobileNumber" />
                            <br />
                            <input type="submit" name="submit" value="Register" class="btn btn-default btn-sm form-control" />
                        </form>
                        <div class="col-md-3"></div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</section>

<?php require('template/footer.phtml') ?>
