<?php require('template/header.phtml') ?>

<!-- Search Field -->
<?php require_once('template/searchBar.phtml');?>

<div id="searchResultDisplay" class="container">
    <?php
    if(isset($view->searchResults) && $view->searchResults != "")
    {
        echo $view->searchResults;
    }
    else
    {
        echo "<h2>No search results</h2>";
    }
    ?>
</div>

<div class="container center-block">
        <ul class="pager">
            <li><a href="search.php?<?php
                echo "category=" . $_GET['category'] . "&search=" . $_GET['search'] . "&order=" . $_GET['order'] . "&page=" . ($_GET['page'] - 1);
                ?>">Previous</a></li>

            <li><a href="search.php?<?php
                echo "category=" . $_GET['category'] . "&search=" . $_GET['search'] . "&order=" . $_GET['order'] . "&page=" . ($_GET['page'] + 1);
                ?>">Next</a></li>
        </ul>
</div>
<?php require('template/footer.phtml') ?>