<?php require('template/header.phtml') ?>

<!-- Link JS -->
<script type="text/javascript" language="JavaScript" src="/js/AJAXConnection.js"></script>
<script type="text/javascript" language="JavaScript" src="/js/infiniteScroll.js"></script>
<script type="text/javascript" language="JavaScript" src="/js/liveSearch.js"></script>
<script>
    window.onscroll = function(ev) {
        if ((window.innerHeight + window.scrollY) >= document.body.offsetHeight) {
            bottomOfPage();
        }
    };

    window.focus = function(ev)
    {
        alert(ev);
    }
</script>
<body onclick="clearSearch()">
<!-- Search Field -->
<section class="container container-fluid">
    <form name="search-function" disabled="">
        <fieldset>
            <legend>Search</legend>
            <div class="form-group col-md-12">
                <div class="form-group col-md-2">
                    <select id="searchCategory" name="category" onchange="handleSearch()" class="form-control col-md-2">
                        <option value="everything">All Departments</option>
                        <option value="violin">Violins</option>
                        <option value="viola">Violas</option>
                        <option value="cello">Cellos</option>
                        <option value="bass">Double Basses</option>
                        <option value="music">Sheet Music</option>
                        <option value="accessory">Accessories</option>
                    </select>
                </div>
                <div class="form-group col-md-10">
                    <input name="searchBar" id="searchBar" onkeypress="return handleKeyPress(event, this.value)" type="text" class="form-control" autocomplete="off" placeholder="Search for an item here" />
                    <ul class="list-group col-md-12" id="hintList" style='position:absolute; z-index: 10' tabindex="1">
                        <!-- AJAX method in JS/search.js injects code here-->
                    </ul>
                </div>

                <div class="form-group col-md-4">
                    <select id="searchOrder" name="order" onchange="handleSearch()" class="form-control col-md-2">
                        <option value="relevant">Most Relevant</option>
                        <option value="highToLow">Price: Highest to Lowest</option>
                        <option value="lowToHigh">Price: Lowest to Highest</option>
                        <option value="newToOld">Date: Newest Adverts</option>
                        <option value="oldToNew">Date: Oldest Adverts</option>
                    </select>
                </div>
                <div class="form-group col-md-2">
                    <label class="checkbox-inline">
                        <input id="searchHasCase" onchange="handleSearch()" type="checkbox" name="hasCase">Has a case
                    </label>
                </div>
                <div class="form-group col-md-2">
                    <label class="checkbox-inline">
                        <input id="searchHasBow" onchange="handleSearch()" type="checkbox" name="hasBow">Has a bow
                    </label>
                </div>
                <input type="hidden" name="page" value="0" />
                <div class="form-group col-md-4">
                    <button class="btn btn-default form-control" type="button" onclick="handleSearch()" id="searchBtn">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </div>
            </div>
        </fieldset>
    </form>
</section>

<div id="searchResultDisplay" class="container">
    <!--    Place items here through AJAX call-->
</div>

<div id="message" class="container">
    <!--    Place messages here through ajax call-->
</div>

<!-- Function to load in adverts once page has rendered -->
<script type = "text/javascript">
    let requestedCategory = window.location.search.substr(3);
    if(requestedCategory === "")
        requestedCategory = "everything";

    var category = document.getElementById("searchCategory");
    category.value = requestedCategory;
    handleSearch();
//    loadMore(createSearchString());
</script>
</body>
<?php require('template/footer.phtml') ?>