<?php require('template/header.phtml') ?>

<form name="pageCount" action="<?php echo htmlentities($_SERVER['PHP_SELF'])?>" method="get">
    <input type="hidden" name="page" value="0">
</form>

<div class="container">
    <h1>Your Adverts</h1>
    <?php
    if(strlen($view->userAdverts) > 0)
    {
        echo $view->userAdverts;
    }
    else
    {
        echo "<h2>It appears you don't have any adverts. </h2>";
        echo "<h3><a href='/post.php'>Post an advert</a></h3>";
    }
    ?>
</div>
<div class="container center-block">
    <ul class="pager">
        <li><a href="user.php?<?php
            echo "page=" . ($_GET['page'] - 1);
            ?>">Previous</a></li>

        <li><a href="user.php?<?php
            echo "page=" . ($_GET['page'] + 1);
            ?>">Next</a></li>
    </ul>
</div>
<?php require('template/footer.phtml') ?>
