<?php require('template/header.phtml') ?>

<div class="container">
    <h1>Your Wishlist</h1>
    <?php
    if(isset($view->userAdverts))
    {
        echo $view->userAdverts;
    }
    else
    {
        echo "<h2>It appears you don't have any adverts in your wishlist</h2>";
        echo "<h3><a href='/index.php'>Search for products</a></h3>";
    }
    ?>
</div>
<?php require('template/footer.phtml') ?>
