<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="A classified advert system created for my Client Server Systems assignment">
    <meta name="author" content="Henry Senior">


    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">

    <!-- Bootstrap theme -->
    <link href="/css/bootstrap-theme.css" rel="stylesheet">

    <!-- Additional Styles-->
    <link href="/css/my-style.css" rel="stylesheet">

    <title><?php echo $view->pageTitle; ?></title>
</head>

<body role=""document">

<!--Navigation-->
<div class="container container-fluid">
    <nav class="navbar navbar-default">
        <div class="container-fluid">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.php">Music Parlour</a>
            </div>

            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="../../login.php"><span class="glyphicon glyphicon-log-in"></span> Login / Register</a></li>
                </ul>
            </div>
        </div>
    </nav>
</div>