<!-- Search Field -->
<section class="container container-fluid">
    <form name="search-function" method="get" action="/search.php">
        <fieldset>
            <legend>Search</legend>
            <div class="form-group col-md-12">
                <div class="form-group col-md-2">
                    <select name="category" class="form-control col-md-2">
                        <option value="everything">All Departments</option>
                        <option value="violin">Violins</option>
                        <option value="viola">Violas</option>
                        <option value="cello">Cellos</option>
                        <option value="bass">Double Basses</option>
                        <option value="music">Sheet Music</option>
                        <option value="accessory">Accessories</option>
                    </select>
                </div>
                <div class="form-group col-md-6">
                    <input name="search" type="text" class="form-control" placeholder="Search for an item here" />
                </div>

                <div class="form-group col-md-3">
                    <label class="checkbox-inline">
                        <input type="checkbox" name="hasCase">Has a case
                    </label>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="hasBow">Has a bow
                    </label>
                </div>

                <div class="form-group col-md-1">
                    <button class="btn btn-default form-control" type="submit">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </div>
            </div>
        </fieldset>
    </form>
</section>