<!-- Link JS -->
<script type="text/javascript" language="JavaScript" src="/js/AJAXConnection.js"></script>
<script type="text/javascript" language="JavaScript" src="/js/infiniteScroll.js"></script>
<script type="text/javascript" language="JavaScript" src="/js/search.js"></script>

<!-- Search Field -->
<section class="container container-fluid">
    <form name="search-function">
        <fieldset>
            <legend>Search</legend>
            <div class="form-group col-md-12">
                <div class="form-group col-md-2">
                    <select id="searchCategory" name="category" class="form-control col-md-2">
                        <option value="everything">All Departments</option>
                        <option value="violin">Violins</option>
                        <option value="viola">Violas</option>
                        <option value="cello">Cellos</option>
                        <option value="bass">Double Basses</option>
                        <option value="music">Sheet Music</option>
                        <option value="accessory">Accessories</option>
                    </select>
                </div>
                <div class="form-group col-md-10">
                    <input name="search" id="searchBar" onkeyup="liveSearchBar(this.value)" type="text" class="form-control" autocomplete="off" placeholder="Search for an item here" />
                    <ul class="list-group col-md-12" id="hintList" style='position:absolute; z-index: 10'>
                        <!-- AJAX method in JS/search.js injects code here-->
                    </ul>
                </div>

                <div class="form-group col-md-4">
                    <select id="searchOrder" name="order" class="form-control col-md-2">
                        <option value="relevant">Most Relevant</option>
                        <option value="highToLow">Price: Highest to Lowest</option>
                        <option value="lowToHigh">Price: Lowest to Highest</option>
                        <option value="newToOld">Date: Newest Adverts</option>
                        <option value="oldToNew">Date: Oldest Adverts</option>
                    </select>
                </div>
                <div class="form-group col-md-2">
                    <label class="checkbox-inline">
                        <input id="searchHasCase" type="checkbox" name="hasCase">Has a case
                    </label>
                </div>
                <div class="form-group col-md-2">
                    <label class="checkbox-inline">
                        <input id="searchHasBow" type="checkbox" name="hasBow">Has a bow
                    </label>
                </div>
                <input type="hidden" name="page" value="0" />
                <div class="form-group col-md-4">
                    <button class="btn btn-default form-control" type="button" onclick="handleSearch()" id="searchBtn">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </div>
            </div>
        </fieldset>
    </form>
</section>